-- Domicilio Editoriales 
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom01','Bucareli','Col. Centro','06000')
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom02','Av México','Col. Santa Cruz','03330')
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom03','Montecito','Nápoles','03810')
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom04','Torre Privanza','Verónica Anzures','11300')
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom05','Montes Urales','Lomas de Chapultepec','11000')
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom06','Calz Independencia','Zona Centro','44100')
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom07','Calz Independencia','Zona Centro','44300')
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom08','Calz Independencia','Zona Centro','44469')
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom09','Prada','Colón Industrial','44940')
INSERT INTO Domicilio_Editoriales(id_domicilio,calle,colonia,cp) VALUES ('dom10','28 de Enero',' Analco','44450')
-- Editoriales
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi01','dom01','Reforma','55231416')
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi02','dom02','El Universal','55101578')
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi03','dom03','Playboy MX','55121014')
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi04','dom04','Salamandra','55458967')
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi05','dom05','FCE','55080808')
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi06','dom06','Amteditorail','33331702')
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi07','dom07','Difusora','33010203')
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi08','dom08','El Occidente','33442569')
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi09','dom09','Alba','33018579')
INSERT INTO Editoriales(id_editorial,id_domicilio,nombre_editorial,telefono_editorial) VALUES ('edi10','dom10','Toukan Mango','33696945')