-- Domicilio Suscriptores
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom01','El Pino','Claveria','01000',15)
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom02','Miguel Aleman','El Potrero','52975',45)
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom03','Ignacio Megia','Santa Maria','13001',01)
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom04','River Plate','Buenavista','450101',45)
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom05','Las Torres','Col. Centro','11000',68)
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom06','San Carlos','Palma Real','40589',48)
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom07','Laurel','Lomas de Batan','40589',13)
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom08','Granjas','Tesitan','40889',10)
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom09','Av Patria','Alfredo Barba','40583',06)
INSERT INTO  Domicilio_Suscriptores(id_domicilio,calle,colonia,cp,no_ext) VALUES ('dom10','San Ramon','Americana','41389',76)
-- Suscriptores
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc01','Javier Hernandez','55101213','dom01')
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc02','Raul Jimenez','55634511','dom02')
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc03','Bruno Díaz','55081412','dom03')
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc04','Ricardo Tapia','55697810','dom04')
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc05','Oliver Reynosa','55556312','dom05')
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc06','Fernanda Ontiveros','33121574','dom06')
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc07','Maria Estrada','33569874','dom07')
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc08','Alejandra Palacios','3356978','dom08')
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc09','Raul Ruiz','33262521','dom09')
INSERT INTO Suscriptores(id_susc,nombre_susc,tel_susc, id_domicilio) VALUES ('suc10','Jose Jimenez','33334112','dom10')