INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub01','edi01','El Reforma',1)
INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub02','edi02','El Universal',2)
INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub03','edi03','Playboy',3)
INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub04','edi06','Quién',4)
INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub05','edi07','Entrepreneur',1)
INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub06','edi08','Rider',2)
INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub07','edi09','Futbol Total',3)
INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub08','edi10','Squire',4)
INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub09','edi01','La Razón',1)
INSERT INTO Publicaciones(id_publicacion,id_editorial,nombre_publicacion, frecuencia) VALUES ('pub10','edi02','El Gráfico',2)