INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom01','Juarez','Independencia','11002')
INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom02','Miguel De La Madrid','Tabacalera','13012')
INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom03','Arbolitos','Roma','41003')
INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom04','Rio Eslava','San Juan','52102')
INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom05','El Salvador','Jardin Balbuena','41002')
INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom06','Manuel Davalos','Santa Cruz','21042')
INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom07','Gaspar Bolaños','Colonias','56031')
INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom08','Oviedo','Independencia','14006')
INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom09','Cosmos','Independencia','32000')
INSERT INTO Domicilio_Escritores((id_domicilio, calle_esc , colonia_esc , cp_esc)  VALUES ('dom10','Julio Cortazar','Independencia','61004')
-- Generos Literarios
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen01','Deportes')
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen02','Comedia')
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen03','Sociales')
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen04','Arte')
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen05','Espectaculos')
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen06','Politica')
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen07','Historia')
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen08','Cine')
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen09','Literatura')
INSERT INTO Generos_Lit(id_genero , genero )  VALUES ('gen10','Ciencia')

-- Escritores
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc01','dom01','gen01','Alberto Chimal')
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc02','dom02','gen01','Guadalupe Nettel')
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc03','dom03','gen02','Bernardo Esquinca')
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc04','dom04','gen04','Valeria Luiselli')
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc05','dom05','gen06','Ignacio Padilla')
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc06','dom06','gen04','Bernardo Bef')
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc07','dom07','gen03','Fernanda Melchor')
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc08','dom08','gen02','Jorge Bone')
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc09','dom09','gen08','Aura Xilonen')
INSERT INTO Escritores(id_escritor ,id_domicilio, id_genero, nombre_escritor) VALUES ('esc10','dom10','gen07','Bibiana Camacho')